transmission.json
The suggested share name was previously transmission-rockon
which is confusing as it's only the data and config that uses this
share not the rockon itself which is stored on another specialized
share.
Fixes #3
=> change share name example to transmission-data. Fixes #3

gogs.json
A Rock-On wrapper around the [Gogs](https://gogs.io/) official [gogs/gogs](https://hub.docker.com/r/gogs/gogs/) Docker image as [discussed on the forum](https://forum.rockstor.com/t/rock-on-requests/41/65). 
The only aspect worth noting is that I split the data in two shares: the configuration share mounted under `/data` in the Docker image, and the git repository share mounted under `/data/git/gogs-repositories`. The latter contains just bare git repositories, nothing gogs-specific (even its wikis are just repositories).
Only a single git repository volume is supported. Allowing volume add support would require the user to keep Gogs user (or organisation) names and the volumes mounted under `/data/git/gogs-repositories` in sync. Not a great idea, I think.
Let me know if there is anything …
=> Added Go Git Service (Gogs).

root.json
@schakrava Found this discrepancy so simple pr to address it. Not sure if I've missed a comment relating to this though.
Consequences as far as I can see are the non appearance of the recently added Symform Rock-on in available Rock-ons.
Not sure how to test these changes though without the repo update so submitting as untested.
=> symform entry missing in root. Fixes #29

gitlab-rc.json
Initiial import, added port 443 from the comments https://github.com/rockstor/rockstor-core/issues/1025. 443 doesn't respond and requires settings to be changed in the image. 
And i was unable to add two UI buttons, but i guess this is expected.
=> Initial import of gitlab rock-on

Sickrage.json
Based on Sickbeard config. Tested on my own Rockstor installation. Has been running well, snatching, downloading and post processing many, many TV shows successfully over the past 24 hours. Sickrage differs from Sickbeard in that it has much better Torrent support.
=> Add Sickrage rock-on from Linuxserver.io

syncthing.json
Thanks to @fago for bringing to light the recent change in discovery port for upstream syncthing as per version v0.12 onwards from 21025 to 21027.
https://docs.syncthing.net/users/firewall.html#local-firewall
and
syncthing/syncthing#2685 (comment)
As of 16 days before @fago 's pull requests has been merged:-
https://github.com/istepanov/docker-syncthing/pull/3
and the consequent Dockerfile on Docker Hub has also been updated:-
https://hub.docker.com/r/istepanov/syncthing/~/dockerfile/
The build details for this image indicate an update 16 days ago followed
by another 4 days ago.
So updating the 21025 entries in syncthing.json to reflect these upstream changes.
Fixes #40
=> syncthing port update to track upstream changes, thanks @fago. Fixes #40

haproxy-letsencrypt.json
This is a haproxy rock-on with integrated letsencrypt client.
On startup, a certificate for all configured hostnames (env variable) is requested from letsencrypt and all 3 weeks the certificates get automatically renewed.
I use this rock-on to make all my configured services (rock-ons) available over https on the standard port 443 and with valid certificates.
As the port 443 is already taken by the rockstor web interface, I run the haproxy on a different port (i.e. 1443) and configured my router to forward internet requests on port 443 to the haproxy port on the rockstor host.
=> add haproxy-letsencrypt rock-on (haproxy with letsencrypt integration)

deluge.json
allow access to the daemon,
since if you can't automate these actions and need to do everything through the web-ui, it just makes the whole thing a bit obsolete.
=> Daemon Port

transmission.json
Transmission currently will set 104:107 by default which usually is not created on the host system.  This resolves inside the containers to debian-transmission.  The issue is that you need to start adding other users to group or have 104:107 set on other rockons to enable them to use the volume from transmission.  This should enable you to do that by setting the UID/GID on creation for transmission. The environment variables added are supported and listed on the github for this rockon - https://github.com/dperson/transmission
This is also a fix for this issue - https://forum.rockstor.com/t/automatically-changing-owner-on-share/1939
=> add UID to transmission rockon

zoneminder-1.30.json
This is for adding a zoneminder v1.30 rock-on. I couldn't get an in-place upgrade working due to changes with mysql (they use mariadb now).  I would also have to add a version select and a lot of if statements to get it to work.  Since people were asking for this, I wanted to get it out the door and that's why the version name is specified.  I had to use my own github repo, I've been looking for months for a solid one and couldn't find one.  I combined two people's work to get this to work.
=> add zoneminder-1.30 rock-on

redirect-http-to-https.json
Solves this issue: https://forum.rockstor.com/t/automatic-http-https-redirection/2052
Tested by installing it locally and suddenly http://rockstor.local/ works :)
=> http->https redirector for web ui

teamspeak3.json
New addition to rockon repository.
Teamspeak3 server is a popular VoIP application. There is one thing a bit tricky for new users with this application that the user needs to read logs in order to get admin access the server once it's installed.
Details on how to do that is added to the "more-info" part of the rock-on.
=> New rock-on: Teamspeak3 server

subsonic.json
`hurricane/docker-subsonic` doesn't exist on docker.io, but `hurricane/subsonic` does.
Likely an outdated reference.
=> Update Subsonic package name

NZBHydra.json
Correct website url to https://hub.docker.com/r/linuxserver/hydra/ from https://hub.docker.com/r/linuxserver/nzbhydra/
=> Correct Website URL

lazylibrarian.json
added the lazylibrarian docker package from [https://hub.docker.com/r/linuxserver/lazylibrarian/linuxserver/lazylibrarian](url)
Modified headphones [https://github.com/rockstor/rockon-registry/blob/master/headphones.json](url) rock-on file since they are basically the same codebase.
Tested on windows uploading json via winscp to current stable version of rockstor. Worked well. No issues.
=> add lazylibrarian rock-on

resilioSync.json
To fix #117 
Tested locally, working fine.
It uses the official Docker container: https://hub.docker.com/r/resilio/sync/
To update an existing btsync rock-on installation: 
- uninstall btsync rock-on
- install resilio sync rock-on
- use the same configuration as for your previous btsync installation (ports and share(s)).
=> add resilio sync rock-on

syncthing.json
Syncthing is now updated to use the linuxserver.io version and can specify UID and GID.  The mapping of the /config share is perfectly compatible with the older mapping of the previous maintainer.  In other words, you can use this json with the older version and keep all settings and not lose anything.
=> moved syncthing to linuxserver version

unifi.json
According to Ubiquity, the STUN port is UDP not TCP. This fixes errors of "STUN Communication Failed" from adopted devices.
=> Fix STUN port protocol

zabbix-xxl.json
Zabbix XXL sets up a full Zabbix Server and MariaDB using three containers linked.  I was pretty impressed this worked and wanted to share.  It should be noted the DB container uses 1 GB memory though (but that's listed in the readme on the docker page). The password has to be hardcoded as we can't grab variables and hardcode at the same time.  Attempting to pass them did not work so I generated a hash to make the hardcoded DB password somewhat complex.  Considering the database is not using a mapped port and restricted to localhost, this should be secure enough to use I hope.
=> Zabbix xxl

netdata.json, root.json
Although Rockstor's dashboard provides a quick and instantaneous overview of most of the server's state, it could be limited for some users who would like to have a more detailed view of the machine's CPU, RAM, DISK, and NET usage.
Its documentation reads:
> netdata is a scalable, distributed, real-time, performance and health monitoring solution for Linux, FreeBSD and MacOS. It is open-source too.
> 
> Out of the box, it collects 1k to 5k metrics per server per second. It is the corresponding of running top, vmstat, iostat, iotop, sar, systemd-cgtop and a dozen more console tools in parallel. netdata is very efficient in this: the daemon needs just 1% to 3% cpu of a single core, even when it runs on IoT.
Notably, netdata allows the users to set specific alerts at custom thresholds, which …
=> Add netdata Rockon

watchtower.json
Watchtower is a container that monitors your local images for updates on dockerhub and the likes. If an image on dockerhub is detected to be newer then your local image. It will stop, pull, start your container(s) so they stay up to date.
=> Watchtower

embyserver.json
Fixes #152.
This updated Rockon includes a new "devices" object to allow users with compatible hardware to mount the corresponding device for hardware transcoding.
It also includes a new ENV variable `GIDLIST` to add system users with access to this device.
For backward compatibility, this keeps the `--net=host` option, but this also means that, as before, the port selection remains without actual use as the default emby ports can be used (8096 for HTTP, and 8920 for HTTPS). Would somebody know what needs this option?
=> Update Emby Rockon

cops.json
As discovered by @lgchris, the container requires a `/books` binding and not `/movies`. See the corresponding issue #165 for details.
Fixes #165 .
=> Fix volume binding

bitwarden-rs-alpine.json, root.json
Rockon for [this unofficial bitwarden docker image](https://github.com/dani-garcia/bitwarden_rs)
Written in rust, uses less resources than the official image, and the image runs on Alpine, so it's even *smaller*.
Some setup required:
* TLS/SSL certs + key: full chain cert must be at `/ssl/certs.pem` and key at `/ssl/key.pem` (I made this share first, turned it into an SMB share, placed the files in, then pointed the Rockon at the share, but as long as the files exist in the right spot you're good to go)
Container port 80 mapped out to whatever, default doesn't really matter so feel free to change it to whatever doesn't clash with existing systems.
Confirmed working on Rockstor 3.9.1-16, Bitwarden 2.8.0 (docker tag 1.5.0-alpine or something close to that), Chrome extension 1.37.0, and …
=> Add Bitwarden-rs alpine

teamspeak3.json
Fix #166 
This PR updates the Teamspeak3 Rock-on to use the official docker image: [https://hub.docker.com/_/teamspeak](https://hub.docker.com/_/teamspeak)
This change is currently **required** as the current image has already been deprecated. See Issue #166 for details and discussion on naming convention.
This has been tested to work on Rockstor-3.9.1-16 by myself and confirmed by the issue author @Noggin01.
@phillxnet, this PR is ready for your attention.
=> Issue166 ts3 official

unifi-linuxserver.json
Updated repo to point to new linuxserver unfi-controller repo since the unifi repo is depracted.  The version is already out of support.  The new repo is under support and has no impact on an existing installation.  It is also recommended by unifi as the preferred docker method.  We also have an option for an extra argument to cap memory but I put that in the more_info section rather than forcing the user to enter it.  This is for https://github.com/rockstor/rockon-registry/issues/191
=> updated unifi-linuxserver

.github/pull_request_template.md
Fixes #194. 
As described in #194, it is proposed to use a template for PR submissions in order to help ensure all required information is provided and in the correct location/format.
@phillxnet, this should work and appear automatically once merged into master.
Ready for you to review.
=> Use a pull-request template for new rock-on submissions

jenkins.json
Text and image update of existing Jenkins CI Rockon. See issue #177 for context.
Summary of changes
- update image
- spaces not tabs
- Improve description, adding docker image reference
Fixes #177 
Ready for review.
Caveat:
This Rock-on's user facing text states/assumes its use of the LTS variant docker image. However we have an outstanding rockstor-core issue (with pending pr fix) that this Rockon depends upon.
Prior to review dependencies:
Issue:
"honour tag element within rock-on json #2014"
https://github.com/rockstor/rockstor-core/issues/2014
Pull request currently pending:
"honour tag element within rock-on json. Fixes #2014"
https://github.com/rockstor/rockstor-core/pull/2016
=> use new official jenkins image. Fixes #177

plex.json
Merge updates
Fixes # .
Add QuickSync option (device) to enable Intel HW transcoding
This pull request proposes to enhance an existing rock-on for the following project:
- name: Plex Rockon
- website: N/A
- description: using existing Plex RockOn definition under underlying …
=> Update Plex Rock-On to allow optional support of Intel QuickSync transcoding

handbrake.json
Fixes #212 .
This pull request proposes to update an existing rock-on for the following project:
- name: HandBrake
- website: [https://handbrake.fr](https://handbrake.fr)
- description: video transcoding with included GUI
- docker image: [https://hub.docker.com/r/jlesage/handbrake](https://hub.docker.com/r/jlesage/handbrake
- is an official docker image available for this project?: N/A
- remove unsupported <u> html tags
- replace mentions of VAAPI with Intel Quick Sync
- replace example device path to the Interl Quick Sync one
- minor edit of "more_info" field
@phillxnet , @mikey0000 , ready for review.
=> Update HandBrake rock-on device description, Fixes #212:

bitwarden-rs-alpine.json
Fixes #208.
This pull request proposes to update a rock-on for the following project:
- name: bitwarden-rs
- website: https://github.com/dani-garcia/bitwarden_rs
- description: Bitwarden password manager server in Rust.
- docker image: https://hub.docker.com/r/bitwardenrs/server
- is an official docker image available for this project?: yes, but this one is smaller and self-contained (for reference, the original looks like it's [spread out over 6 containers](https://help.bitwarden.com/images/hosting/docker-ps.png))
=> Bitwarden rs alpine

nginx.json
Use the official nginx image, but users will need to add a `default.conf` file to their nginx config share for the server to work. This is required as the mounted volume will shadow the `config` directory in the container that nginx tries to read the config file from.
=> Add nginx rockon

postgres-9.5.json, root.json
Net New.
Fixes #216 
- name: PostgreSQL 9.5 (using official docker container)
- website: postgresql.org
- description: allow installation of PostgreSQL 9.5(.21) as a rockon, so it can be used by other applications that require a RDBMS.
- docker image: https://hub.docker.com/_/postgres
- is an official docker image available for this project?: yes, this is the official docker image
=> Issue216 PostgreSQL 9.5 rockon

foldingathome-linuxserver.json, root.json
Includes:
- root.json addition.
- Nvidia env hard wired for simplicity in anticipation of future GPU capabilities within the Rock-on system via a newer docker subsystem.
Fixes #219
@FroggyFlox Ready for review.
Note that I have slight concerns about the use of the '@' char in the root.json file. Easier for us to test post pull request submission however.
- name: Folding@home
- website: https://foldingathome.org/
- description: "...distributed computing project for simulating protein dynamics, including the process of protein folding and the movements of proteins implicated in a variety of diseases." quoted from their about page. This project is of recognised scientific import and depends on community members …
=> add new Folding@home Rock-on using the linuxserver.io docker image. Fixes #219

postgres-10.6.json, root.json
See issue text for info/context.
Fixes #221
This pull request simply harmonises our 2 postgresql Rock-ons with regard to their user facing text and options. Our 9.5 version was influenced by our 10.6 version, but the latter was merged later. Both were community contributions thus:
For 9.5 see:  pr #217 by @Hooverdan96 
For 10.6 see: pr #190 by @holmesb 
N.B. A key element of this harmonising was the adding of admin user and password elements taken from 10.6 (added by @Hooverdan96) and retrofitted to 9.5.
=> add postgres-10.6.json to root.json & normalise with 9.5 variant. Fixes #221

nodered.json, root.json
Fixes # .
- name: NodeRed
- website: https://nodered.org
- description: Low-code programming for event-driven applications. This is programming tool for wiring together hardware devices, API's and …
=> add NodeRed rock-on

minio.json, root.json
Fixes # 231.
- name: MinIO
- website: https://min.io/
- description: MinIO is an S3-compatible object storage server.  Requires Rockstor 3.9.2-39 or later.
- docker image: …
=> Add MinIO Rock-on #231

root.json, watchtower_official.json
Fixes #233  .
This Pull Request will introduce the official docker container as a new Rock-on
modifier: root.json - added new Rock-On
new: watchtower_official.json - official docker container
- name: Watchtower Official
- website: https://containrrr.github.io/watchtower
- description: Official container of Watchtower project to monitor and update existing Rock-ons periodically.
- docker image: https://hub.docker.com/r/containrrr/watchtower
- is an official docker image available for this project?: yes, this is it.
=> Addresses #233 Watchtower Rock-on Issue (Part 1) - new official Watchtower container

netdata-official.json, root.json
Fixes #236.
- name: Netdata
- website: https://www.netdata.cloud/
- description: Netdata is a scalable, distributed, real-time, performance and health monitoring solution for Linux, FreeBSD and MacOS. Out of the box, it collects 1k to 5k metrics per server per second. It is the corresponding of running top, vmstat, iostat, iotop, sar, systemd-cgtop and a dozen more console tools in parallel. Netdata is very efficient in this: the daemon needs just 1% to 3% cpu of a single core.
- docker image: https://hub.docker.com/r/netdata/netdata
- is an official docker image available for this project?: Yes, this PR uses it.
=> Add new Netdata (official) rock-on

root.json, scrutiny.json
- name: Scrutiny
- website: [https://github.com/AnalogJ/scrutiny](https://github.com/AnalogJ/scrutiny)
- description: Scrutiny is a Hard Drive Health Dashboard & Monitoring solution, merging manufacturer provided S.M.A.R.T metrics with real-world failure rates.
- docker image: [https://hub.docker.com/r/linuxserver/scrutiny](https://hub.docker.com/r/linuxserver/scrutiny)
- is an official docker image available for this project?: Yes
=> New Rock-on: Scrutiny

NZBHydra.json, NZBHydra2.json, root.json
When looking at the pages on the Docker Hub for [linuxserver.io/hydra](https://hub.docker.com/r/linuxserver/hydra/), it mentions in the Application Setup section that that image is deprecated, pointing the user to [linuxserver/nzbhydra2](https://hub.docker.com/r/linuxserver/nzbhydra2) instead. I have been using a self-defined image for NZBHydra2 for some time, so I have tidied up the configuration and shared here.
Note: NZBHydra2 no longer allows you to import you existing NZBHydra configuration.
- name: linuxserver.io NZBHydra2
- website: https://github.com/theotherp/nzbhydra2
- description: NZBHydra2 is meta search application for NZB indexers, offering a unified search experience over several different indexers, …
=> Added NZBHydra2, as linuxserver.io have deprecated older hydra image

NginxProxyManager.json
As IPv6 is currently disabled, we also have to disable it for this rock-on via environment variables otherwise nginx will not start:
```
2021/02/11 20:35:31 [emerg] 14860#14860: socket() [::]:8080 failed (97: Address family not supported by protocol)
2021/02/11 20:35:32 [emerg] 14869#14869: socket() [::]:8080 failed (97: Address family not supported by protocol)
2021/02/11 20:35:33 [emerg] 14878#14878: socket() [::]:8080 failed (97: Address family not supported by protocol)
2021/02/11 20:35:34 [emerg] 14887#14887: socket() [::]:8080 failed (97: Address family not supported by protocol)
2021/02/11 20:35:35 [emerg] 14896#14896: socket() [::]:8080 failed (97: Address family not supported by protocol)
2021/02/11 20:35:36 [emerg] 14905#14905: socket() [::]:8080 failed (97: Address family not …
```
=> Fix nginx-proxy-manager for rockstor 4

root.json, wsdd.json
Fixes #295 .
- name: wsdd (Web Service Discovery Daemon)
- website: based on https://github.com/christgau/wsdd
- description: A container for Linux systems running samba, so that Windows 10 version 1511 or higher will display the host in the Network folder. This rockon setup is only for workgroup based networks, as rockons cannot currently handle either/or selection fields. Due to the nature of the wsdd, this rockon requires the --net=host option.
- docker image: https://hub.docker.com/r/kosdk/wsdd
- is an official docker image available for this project?: No. There are more popular ones, but they only offer the amd64 architecture. The one used here allows for arm v7,v8 and amd64 usage and is the most recent of …
=> Web Services Discovery Daemon (Wsdd) rockon

minio.json
Update for separate API and console ports in MinIO Docker image.
Fixes #302 .
- docker image: <link to image page on docker hub>
- is an official docker image available for this project?:
=> Update for separate API and console ports in MinIO Docker image

qbittorrent_lsio.json, root.json
Since there has not been any updates on Pull Request #291, wanted to submit a PR that includes requested changes and some additional (cosmetic) updates to the originally proposed Rockon. It is based on the same image as the original PR. Additionally, I have exposed the WEBUI_PORT environment variable to account for the need to have both container port and Rockon port to match (with appropriate description and links).
- name: qBittorrent
- website: https://qBittorrent.org
- description: this Rockon runs the qBittorrent client with a WebUI. Since the uTorrent client will be deprecated and qbittorrent offers additional functional like sequential downloads compared to the Transmission client, this should be a good …
=> Add qBittorrent Rockon based on PR #291

airsonic-advanced.json, root.json
Airsonic Rock-On proposal config for a Subsonic replacement.
Fixes #307  .
- name: Rockstor rockon-registry / Airsonic MPD.
- website: https://github.com/linuxserver/docker-airsonic-advanced
- …
=> #307 Create airsonic-advanced.json

omada-controller.json, root.json
Fixes #332 .
- name: Omada Software Controller
- website: https://www.tp-link.com/us/support/download/omada-software-controller/
- description: This docker image contains the software controller for the TP-Link's Omada networking devices. This software controller is needed when you want to manage all your Omada devices from a single WebUI, and when you want special features which depend on it. 
- docker image: https://hub.docker.com/r/mbentley/omada-controller
- is an official docker image available for this project?: No.
=> #332 Add project Omada Controller as Rock-on

minetest.json, root.json
Fixes # .
- name: Minetest
- website: minetest.net
- description: Rockon for minetest server
- docker image: r/linuxserver/minetest
- is an official docker image available for this project?: 
using the …
=> add minetest server

pi-hole.json
Fixes #305. 
Update Rockon with net=host option to easily enable Pi-hole use as dhcp server.
Remove superfluous port mappings due to net=host option being active.
Cosmetic description adjustments and to highlight net=host option being active
This pull request proposes to update the pi-hole Rockon.
- official docker image: (https://hub.docker.com/r/pihole/pihole) - unchanged from previous Rockon version
=> Pi-Hole Rockon update to enable dhcp server

README.md
Fixes #350 . Dependency on PR https://github.com/rockstor/rockstor-doc/pull/452 which will have moved most of the contribution aspects from the Rock-on Readme to the canonical documentation spot (https://rockstor.com/docs/contribute/contribute_rockons.html and others)
N/A - documentation update only
- N/A - documentation update only
=> Refactor README.md to sync with Rockstor Documentation

OpenSpeedTest.json, root.json
Fixes #354 .
- name: SpeedTest by OpenSpeedTest
- website: https://openspeedtest.com/
- description: SpeedTest by OpenSpeedTest™ is a Free and Open-Source HTML5 Network Performance Estimation Tool. Setup for http connection only.
- docker image: [<link to image page on docker hub>](https://hub.docker.com/r/openspeedtest/latest)
- is an official docker image available for this project?: yes, above is the offical one.
=> Add Rockon for SpeedTest  tool

WireGuardEasy.json
Fixes #361.
- docker image: https://github.com/wg-easy/wg-easy/pkgs/container/wg-easy
Tested using the same configuration as the previous incarnation. No issues experienced, and WireGuard tunnel works as expected.
=> update WireGuard docker image (#361)

filebrowser.json, root.json
Fixes #364  .
- name: Filebrowser
- website: https://filebrowser.org/
- description: filebrowser provides a file managing interface within a specified directory and it can be used to upload, delete, preview, rename and edit your files. It allows the creation of multiple users and each user can have its own directory. It can be used as a standalone app.
- docker image: [<link to image page on docker hub>](https://hub.docker.com/r/filebrowser/filebrowser)
- is an official docker image available for this project?: Official image, using the version with linuxservers S6 as base layer
=> New Filebrowser Rockon

2FAuth.json, root.json
Fixes #360  .
Note, since this is a draft PR, the root.json has not been updated yet for this PR, in case the direction (aka different docker target) is more viable.
Currently, the installation completes, the container seems to be the running its processes, however the UI screen is blank. Needs further investigation whether it's related to container itself or the Rockon json/other. If anybody has experience with this container/application, please consider helping analyze the issue.
- name: 2FAuth (Desktop authenticator)
- website: https://docs.2fauth.app/
- description: 2FAuth is a web based self-hosted alternative to One Time Passcode (OTP) generators like Google Authenticator, designed for both mobile and …
=> Create F2Auth Rockon

jellyfin-linuxserver.json
Simplifies configuration to enable hardware support in Jellyfin.
Empty string as a default seems to work reasonably, and adding hardware support works. 
Fixes #376.
This pull request proposes to add a new rock-on for the following project: N/A
- docker image: …
=> Add `DOCKER_MODS` support to Jellyfin rockon

lms_latest.json
Fixes #381.
Changes performed:
- Replace Docker Image with new community version (renamed to Lyrion Media Server after Logitech shut project down).
- Update Parameter Changes/Description
- Formatting
- new docker image: [<link to image page on docker hub>](https://hub.docker.com/r/lmscommunity/logitechmediaserver/)
- is an official docker image available for this project?: Yes - project migrated from Logitech to community: https://lyrion.org/
=> Replace LMS docker image with new community version (#381)

WireGuardEasy.json
Fixes #388 .
- The developer deprecated clear text password earlier this year with a hash password that can be generated based on a script they are providing.
same author, however, the developer is recommending to use the image on Github instead of Docker hub:
ghcr.io/wg-easy/wg-easy
- update image source
- replace password parameter with password hash parameter
- update description with instructions for hash.
- fix indentation formatting (tab to space)
- increased version number
I have installed it using the same parameters as before, with the exception of the password now being entered as a hash value. Works well for me, connectivity from outside the network operates just as before it broke. The admin WebUI is accessible with the underlying password, so that transition works as well.
=> Replace deprecated clear text password with hash

lms_latest.json
Fixes #400 .
- name: lyrion media server (formerly Logitech Media Server)
- website: http://lyrion.org
Updating to docker image that lyrion migrated to as old image name was deprecated. No functionality changes
=> Update LMS to new docker image source (#400)

netalertx.json, root.json
Fixes #396  .
- name: NetAlertX
- website: https://netalertx.com/
- description: It is a IDS and it uses net=host. It has a WebUI reminiscent of pi-hole.
- docker image: …
=> Creates a Rockon for the IDS NetAlertX

gollum.json
- update docker image
- update descriptions
Fixes #410  .
- docker image: https://hub.docker.com/r/gollumwiki/gollum
- is an official docker image available for this project?: yes, switching to official image with this PR
=> Switch to official Gollum image (#410)

pi-hole.json
Fixes #427  .
- Address breaking changes between pi-hole v5.x and v6.x
- some text cleanup, convert to Unix LR and replace tabs with spaces.
- docker image: https://hub.docker.com/r/pihole/pihole
- is an official docker image available for this project?: yes
=> Update pi-hole to version 6.x (#427)

foldingathome-linuxserver.json
Fixes #431 .
Adjust for breaking changes with version 8.x of the Folding @ Home client and hence linuxserver.io's changes to parameters:
- transition to external web-UI
- token requirement for startup
- machine name to identify node in external web-UI
- docker image: [<link to image page on docker hub>](https://hub.docker.com/r/linuxserver/foldingathome)
- is an official docker image available for this project?: No
=> Fix breaking changes in Folding@Home Rockon (#431)

transmission-with-openvpn.json
Adds the `TRANSMISSION_WEB_UI` environment variable to config for the `Transmission - OpenVPN` image with documentation based on the [official image docs](https://haugene.github.io/docker-transmission-openvpn/config-options/#alternative_web_uis). 
Tried this with both `default` as the setting, as well as `combustion`, `flood-for-transmission` and `transmissionic` and it works fine. Users that re-install the image will just need to add `default` for the variable to continue with the existing experience.
I've also updated the rock-on version and website to link to the project website rather than the docker image itself.
Fixes #433 .
This pull request updates the existing `transmission-with-openvpn` rock-on.
=> Support alternate web UI for Transmission OpenVPN

root.json, transmission-ls.json
Fixes #436 
- name: Transmission
- website: https://transmissionbt.com/
- description: We already have a Rockon definition for Transmission. However, it is rather outdated so I'm proposing an alternative based on the LinuxServer builds. I'm adding this as a separate Rockon definition because I'm unsure of the upgrade procedures for the existing one. I'm happy to edit the existing `transmission.json` instead if that's a safe route for existing installations.
- docker image: https://hub.docker.com/r/linuxserver/transmission
- is an official docker image available for this project?: No.
=> Add Transmission based on newer LinuxServer image (#436)

forgejo-runner.json, root.json
Fixes #444
- name: Forgejo Actions runner
- website: https://docs.codeberg.org/ci/actions/
- description:  Self-hosted Forgejo actions runner.
- docker image: https://codeberg.org/phillxnet/forgejo-runner-wrapper
- is an official docker image available for this project?:  yes, but it is correctly minimalist; hence the layered helper image development.
Note: Adds a Forgejo runner Rock-on using a custom docker wrapper image `FROM:` the official code.forgejo.org/forgejo/runner upstream image.
=> Forgejo runner #444

forgejo.json, root.json
Fixes #449.
- name: forgejo
- website: https://forgejo.org/
- description:  forgejo is a self-hosted lightweight software forge. Easy to install and low maintenance
- docker image: https://codeberg.org/forgejo/-/packages/container/forgejo/12 as well as latest postgres db from docker hub
- is an official docker image available for this project?: yes
---
[EDIT phillxnet]
- Doc reference for docker implementation: https://forgejo.org/docs/latest/admin/installation/docker/
=> New Rockon for forgejo [#449]

README.md, filebot-node.json, ghost.json, pocketmine.json, zabbix-xxl.json
Fixes #479
Unquote a number of intentionally integer values,
that were inadvertently entered as strings (quoted).
Update README.md regarding:
- a missing integer specification.
- Bytes for min_size rather than KB.
- Trivial formatting char addition.
---
Associated with on-going devleopment within the following repo: https://github.com/rockstor/rockon-validator
Specivially: https://github.com/rockstor/rockon-validator/issues/45
=> Resolve quoted 'integer' value instances #479
