rockstor/rockon-registry

crashplan.json, symform.json
Both working on my own Rockstor server today.
This is two rockons that have been wanted for a while :+1:
=> Added both Symform and Crashplan to the registry.

deluge.json
changed some of the indents to make the file more readable.
=> readability

plexpy.json, root.json
Add Plexpy to the rockon registry
=> Add Plexpy

mariadb.json
MariaDB database, based on <https://hub.docker.com/r/linuxserver/mariadb/>
=> added MariaDB rock-on

rocketchat.json, root.json
Adding [Rocket.Chat](https://rocket.chat/) rock-on.
this was my first rock-on, so I appreciate any hint for improvement. Eg.
- I was not fully sure, if I specified the linking of both Docker container correctly
Thanks for creating RockStore!
=> Add Rocket.Chat rock-on

transmission.json
=> Add volume_add_support to Transmission.

ghost.json
Ghost rock-on for writing blogs, super lightweight and from official sources (docker)
=> ghost blog writer

ecodms.json
This is a rockon which brings ecoDMS document management system to rockstor.
=> add ecoDMS rock-on

uTorrent.json
**uTorrent Rock-on**
Created the Rock-on using [dbarton](https://hub.docker.com/r/ekho/utorrent/) docker image. Thanks to @phillxnet for all of his help to get this working.
Please if you locking to create your own Rock-on check this [thread](https://forum.rockstor.com/t/request-rockon-utorrent/1824/15)
=> U torrent Rock-on

sickrage.json
Add rock on config for subsonic (http://www.subsonic.org/pages/index.jsp) using https://hub.docker.com/r/hurricane/docker-subsonic/
=> Add subsonic rockon config

plex.json
Also fix some formatting.
See https://github.com/rockstor/rockstor-core/issues/1209
=> Fix some formatting for plex.json

collabra-online.json
Collabora Online Development Edition (CODE) is an online office suite based on libreoffice which can be *integrated with owncloud and nextcloud*. It allows viewing and editing office documents in all popular office file formats, including text documents (docx, doc, odt,…), spreadsheets (xlsx, xls, ods,…) and presentations (pptx, ppt, odp,…).
This rock-on uses the official docker image available here:
https://www.collaboraoffice.com/code/
https://hub.docker.com/r/collabora/code/
=> Add Collabora CODE rock-on

crashplan.json
Created a rockon for crashplan that works headless. It requires some active copying of credentials to a desktop with UI to make use of it. 
https://support.crashplan.com/Configuring/Using_CrashPlan_On_A_Headless_Computer
=> Crashplan rockon

FreshRSS.json
Took a couple of tries to install, but I think that's because of an issue specific to my server (every rock-on seems to take a few tries to install right now...)
Worked smoothly with a SQLite DB after that.
=> Adding FreshRSS

uTorrent.json
Had some issues with utorrent running as default 666 UID and GID. The base docker has environment variables for  UID and GID, which I added into the json.
=> Utorrent - added changeable UID and GID from base docker spec

README.md
Removed "optional" from the descriptions of a couple of fields that are not actually optional and also clarified the options array field.
=> Readme corrections and clarifications

README.md
adds specifications for optional ui and slug object at top level and ui value in port object.
=> adding more optional descriptions to json spec

radarr.json
Needed to run custom scripts not located in default directories for docker and just to allow for media to be placed in multiple directories.
=> changed radarr spec to allow for storage volume changes. 

tftpserver.json
Very simple rockon to implement a tftp server on rockstor
=> Add tftpserver rockon

bitcoind.json
A simple rockon with the full node bitcoin server based on the [kylemanna/bitcoind](https://hub.docker.com/r/kylemanna/bitcoind/) docker image.
=> Add bitcoind rockon

booksonic.json
Added BookSonic to the rockon registry, it includes GID/UID and is a book streaming server.  used the linuxserver container
=> add booksonic rockon

root.json, transmission-with-openvpn.json
Re-opening #133 but this time from a branch. I'm working on getting the proxied version going as well, but in the meantime, this *is* a viable solution. 
For futher description and previous discussion, see #133 .
=> Add Transmission through OpenVPN

ghost.json
Upstream issue and resolution: https://github.com/docker-library/ghost/issues/69  
Previously opened issue (closed and reopened because of branching issues): https://github.com/rockstor/rockon-registry/pull/151  
Installed and appears to be working on my installation.
=> update ghost.json to resolve breaking changes in v1

gollum.json
Working on my local installation v3.9.1-0
https://hub.docker.com/r/adtac/gollum-alpine/
| Container | Device |
|------------|---------|
| 8080        | 8082     |
Container: /wiki
=> Add gollum rock-on

README.md
Add the description of the newly-supported "devices" object to the README, following merge of https://github.com/rockstor/rockstor-core/pull/1962.
=> Add description of "devices" object to README

minecraft.json
Initial commit. Adds a docker container for minecraft.
=> initial commit of minecraft.json

medusa.json, root.json
json file for the medusa PVR docker
=> Medusa Rockon

cardigann.json
Cardigann is like Jackett but maintained differently, and more open to non-private trackers.
=> add cardigann rock-on

Jdownloader2.json
As requested on my post I created the pull request to add Jdownloader rockon :)
=> add jdownloader2 rock-on

nextcloud-official.json, root.json
Fixes #43. 
Update `nextcloud-official.json` rock-on in a new PR as per @phillxnet recommendation.
=> Update Nextcloud-official according to #145 comments.

root.json, tautulli.json
Fixes #256  .
- name: Tautulli
- website: https://tautulli.com/
- description: Tautulli is a python based web application for monitoring, analytics and notifications for Plex Media Server. It will supplant Plexpy which is now unmaintained and will be deprecated in the near future.
- docker image: https://hub.docker.com/r/tautulli/tautulli
- is an official docker image available for this project?: yes, this is it
=> New Rock-on: Tautulli

nodered.json
- docker image: https://hub.docker.com/r/nodered/node-red
- is an official docker image available for this project?: yes
=> Update node red volume according to container docs

README.md
Fixes #320.
Add Architecture Designations/explanations to the Readme file.
=> Update Rockon Readme with Architecture Designation and Format instructions

duplicati-lsio.json
correct GID config option description following the initial (probably) copy&paste;
Fixes a tiny typo;
This pull request proposes to correct a tiny typo which might cause confusion.
n/a
=> correct GID config option description

duplicati-lsio.json
Fixes #404  .
- no changes to docker image and existing settings.
- added required database encryption key environment variable
- cleaned up description and additional instructions
=> Update duplicati Rockon

forgejo-runner.json
A minor info/cosmetic follow-up re the more_info contents of the recently merged Forgejo runner rock-on in:
- Forgejo runner #444 #446
=> Forgejo runner - more_info clarification #447
